### ISSUE TITLE
你好，请问在laserMapping中是如何实现icp的呢？

### ISSUE THREAD

**Issue by RuizhiChang** [h-k8888/FAST_LIO_NOTED#1]
在laserMapping,cpp中的第970行附近，有一行注释/*** ICP and iterated Kalman filter update ***/，可以麻烦简单讲一下吗。

**Comment by h-k8888** [comment]
定义状态时，指定了esikf中调用以下点到面的icp计算：
https://github.com/h-k8888/FAST_LIO_NOTED/blob/dc6ba3e972b2afa5b3848e4b8241de0c93f3bee7/src/laserMapping.cpp#L658


> 在laserMapping,cpp中的第970行附近，有一行注释/*** ICP and iterated Kalman filter update ***/，可以麻烦简单讲一下吗。

**Comment by RuizhiChang** [comment]
> 定义状态时，指定了esikf中调用以下点到面的icp计算：
> 
> https://github.com/h-k8888/FAST_LIO_NOTED/blob/dc6ba3e972b2afa5b3848e4b8241de0c93f3bee7/src/laserMapping.cpp#L658
> 
> 
> 
> 
> 
> > 在laserMapping,cpp中的第970行附近，有一行注释/*** ICP and iterated Kalman filter update ***/，可以麻烦简单讲一下吗。
> 
> 
> 
> 
好的，谢谢您
